version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "assets/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd assets; yarn install

      - save_cache:
          paths:
            - assets/node_modules
          key: v1-dependencies-{{ checksum "assets/package.json" }}

      - run: cd assets; yarn tslint
      - run: cd assets; yarn prod
